import { ReactNode } from "react";
import Navigation from "./_components/Navgation";
import { Metadata } from "next";
import Logo from "./_components/Logo";
import "@/app/_styles/globals.css";

export const metadata: Metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body className="bg-primary-950 text-primary-100 min-h-screen">
        <header>
          <Logo />
          <Navigation />
        </header>

        <main>{children}</main>
      </body>
    </html>
  );
}
